### ISSUE TITLE
Tool doesn't allow choosing group id

### ISSUE THREAD

**Issue by esuomi** [lovromazgon/kafka-offset-setter#1]
Looks like this tool is now semi-hardcoded to set only the status of `"logstash"` group id. Editing it manually by changing the key `group.id` in `kafka.properties` but that's a bit roundabout way to get around it. Instead it would make more sense to provide setting the group id as another commandline option.

**Comment by lovromazgon** [comment]
Actually the included properties file is just an example. You should create your own properties file (possibly more of them) and choose it with the -c/--config parameter at runtime.
I agree it would probably be useful to have it as a command-line option, but since this is just a small hack and it sufficiently covers my use case I will currently not invest the time to add it (maybe in the future). But you are invited to help, make a fork and add it if you wish.

**Comment by lovromazgon** [comment]
Well, the time has come when I also needed this feature :smile: 
In version [v0.0.2](https://github.com/lovromazgon/kafka-offset-setter/releases/tag/v0.0.2) the option `-i` (`--inline-config`) was added. With `-i` you can supply a property which would essentially be in `kafka.properties`. For example `-i group.id=logstash` would change the `group.id` to `logstash`. You can supply multiple `-i` options.
